### ISSUE TITLE
Build on OSX fails

### ISSUE THREAD

**Issue by masterkain** [lastfm/Fingerprinter#1]
Hello,
I'm trying to compile Fingerprinter on Mac OSX Snow Leopard, using macports.

Packages:
    sudo port install cmake fftw-3 taglib libmad curl libsamplerate

This is the trace: http://pastie.org/private/oupffouezfmzhmndjrszq

**Comment by daviddd** [comment]
any news on this?

**Comment by lukpueh** [comment]
Try to deinstall port (and maybe fink as well). Get yourself homebrew: http://mxcl.github.com/homebrew/ And install with:
     brew install lastfmfpclient
or
     brew install lastfm_fplib
For me it worked.

**Comment by sampsyo** [comment]
I think this is caused by a mistake in the CMake script. This fixed building the library (not sure about the command-line tool) for me:
https://gist.github.com/805186

Also, on MacPorts, you'll want the "fftw-3-single" port (not (just?) "fftw-3").

**Comment by krachtstefan** [comment]
Thanks @sampsyo. The patch made it work for me too!

**Comment by hbmartin** [comment]
Can anyone compile this as a static binary for me and post that? I'd be extremely grateful.
