### ISSUE TITLE
Building on Ubuntu 12.04 fails.

### ISSUE THREAD

**Issue by PocketSam** [lastfm/Fingerprinter#2]
Everything seemed fine untill.

Linking CXX executable bin/lastfm-fpclient
/usr/bin/ld: cannot find -lfplib
collect2: выполнение ld завершилось с кодом возврата 1
make[2]: **\* [bin/lastfm-fpclient] Ошибка 1
make[1]: **\* [CMakeFiles/lastfm-fpclient.dir/all] Ошибка 2
make: **\* [all] Ошибка 2

Is it an error with build script?

**Comment by evilrix** [comment]
Thank you. This is now fixed.
